version: '3.3'

services:
  saros-db:
    container_name: ${PROD_DB_HOST}
    image: postgres:14-alpine3.14
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - ${PROD_DB_PORT}:5432
    volumes:
      - ${PROD_DB_NAME}:/var/opt/db
    networks:
      - saros-network

  saros-api:
    container_name: saros-api
    image: perfectvint/saros-api:latest
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
      JWT_SECRET_ACCESS: ${PROD_JWT_SECRET}
    depends_on:
      - saros-db
    ports:
      - "8080:8080"
    networks:
      - saros-network

volumes:
  saros-db:
    driver: local

networks:
  saros-network: