server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:db/prod/changelog.xml
    enabled: true

jwt:
  secret:
    access: ${PROD_JWT_SECRET}

pagination: 12
