server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:
    access: ewJq24Vw/33NqwiIEC5KdFD44rMa7S3ScGMPWCli/MUfb3AkS6HVE0bs9FqwUI5gr0MRGb8L5VF+KjpigLcryZJO2+MKKK0Ba5rkgbcioHs=
