name: SAROS-API DEPLOY

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: self-hosted
    env:
      app_name: saros-api
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Package app
        run: /opt/maven/bin/mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t saros-api:latest .

      - name: Push Docker image
        run: |
          docker tag saros-api:latest ${{ secrets.DOCKER_USERNAME }}/saros-api
          docker push ${{secrets.DOCKER_USERNAME}}/saros-api:latest

      - name: Run the application
        run: docker-compose up -d
