name: SAROS API CD

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkin
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: ls
        run: ls -la

      - name: Build and package Spring Boot app
        run: /opt/maven/bin/mvn clean package -DskipTests

      - name: Run the application
        run: docker-compose up -d